# Generated by Django 4.2.20 on 2025-04-13 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublishingJob",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the publishing task.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("PROCESSING", "Processing Content"),
                            ("PREVIEW_READY", "Preview Ready"),
                            ("PUBLISHING", "Publishing to WeChat"),
                            ("PUBLISHED", "Published Successfully"),
                            ("FAILED", "Processing/Publishing Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the publishing job.",
                        max_length=20,
                    ),
                ),
                (
                    "original_markdown_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the originally uploaded Markdown file.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "original_cover_image_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the originally uploaded cover image.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata extracted from the markdown file (title, author, etc.).",
                        null=True,
                    ),
                ),
                (
                    "thumb_media_id",
                    models.CharField(
                        blank=True,
                        help_text="WeChat permanent media ID for the cover image (thumb_media_id).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "preview_html_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the generated HTML preview file within MEDIA_ROOT.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "wechat_media_id",
                    models.CharField(
                        blank=True,
                        help_text="WeChat media ID of the published draft/article.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Stores error details if the job failed.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the job was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the job was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publishing Job",
                "verbose_name_plural": "Publishing Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
