# Generated by Django 4.2.20 on 2025-04-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishingjob",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when the article was successfully published to WeChat.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Metadata extracted (title, author, etc.) and Cloudinary cover URL.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="original_cover_image_path",
            field=models.CharField(
                blank=True,
                help_text="Relative path to the locally saved original cover image (for WeChat re-upload if needed).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="original_markdown_path",
            field=models.CharField(
                blank=True,
                help_text="Relative path to the locally saved original Markdown file.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="preview_html_path",
            field=models.CharField(
                blank=True,
                help_text="Relative path to the generated HTML preview file.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="thumb_media_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="WeChat permanent media ID for the cover image (thumb_media_id).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="publishingjob",
            name="wechat_media_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="WeChat media ID of the published draft/article.",
                max_length=255,
                null=True,
            ),
        ),
    ]
